export const ORDER_STATUSES = {
   SHOPPING_CART: 'SHOPPING CART',
   IN_PROCESSING: 'IN PROCESSING',
   CONFIRMED: 'CONFIRMED',
   BEING_DELIVERED: 'BEING DELIVERED',
   DELIVERED: 'DELIVERED',
   RECEIVED: 'RECEIVED',
   FAILED: 'FAILED',
}